var gamevars_en = {
    banner: [
        '<span class="index">© ShellSaga, All rights reserved.</span>',
        "   _____            _ _ _____                   ",
        "  /  ___| |        | | /  ___|                  ",
        "  \\ `--.| |__   ___| | \\ `--.  __ _  __ _  __ _ ",
        "   `--. \\ '_ \\ / _ \\ | |`--. \\/ _` |/ _` |/ _` |",
        "  /\\__/ / | | |  __/ | /\\__/ / (_| | (_| | (_| |",
        "  \\____/|_| |_|\\___|_|_\\____/ \\__,_|\\__, |\\__,_|",
        "                                     __/ |      ",
        "                                    |___/       ",
        "                                          © 2024",
    ],
    welcomeLetter: [
        'Welcome! If you are new to the game, here are some tips: ',
        "<br>",
        'Look at your surroundings with the command "<span class="command">ls</span>"',
        'Move to a new location with the command "<span class="command">cd LOCATION</span>"',
        'You can backtrack with the command "<span class="command">cd ..</span>"',
        'Interact with things in the world with the command "<span class="command">less ITEM</span>"',
        "<br>",
        'If you forget where you are, type "<span class="command">pwd</span>"',
        "<br>",
        'Go ahead, explore. I hope you enjoy what you find. Do <span class="command">ls</span> as your first command',
        "<br>",
    ],
    homeMoveMessage: "You have moved to Home. You are in the comfort of your own home.",
    westernForestMoveMessage: [
        "You have moved to WesternForest. You enter and travel deep into the forest. Eventually, the path leads to a",
        "clearing with a large impressive building. A sign on it reads: Spell Casting Academy: The Elite School of",
        "Magic.",
    ],
    northernMeadowMoveMessage: "The serene Northern Meadow welcomes you.",
    locationsString: "Locations:",
    itemsString: "Items:",
    rootString: "You have come home!",
    firstRoomString: "You are at the first room. ",
    noLocationString: "There is no place called ",
    commandString: "Command",
    notFoundString: "not found",
    whereString: "You are in ",
    noItemString: "There is no ",
    hereString: " here",
    noLessString: "Pick a different item to less.",
    nothingInterestingString: "Nothing interesting happens.",
    signInteractMessage: [
        "Spell Casting Academy: The Elite School of Magic Today Only: Free Introductory Lessons!",
        "Novices welcome!",
    ],
    backSignInteractMessage: [
        "If you ever want to go directly Home, just type 'cd ~' or just plain old `cd' and you'll come back Home.",
        "Getting back might be more difficult though.",
    ],
    spellAcademyMoveMessage: [
        "You have moved to SpellCastingAcademy. The halls are filled the hustle and bustle of academy students",
        "scurrying to and from classes. The inside of the academy is as impressive as it is on the outside with a",
        "high ceiling and gothic arches, it seems even larger on the inside.",
    ],
    hurryingStudentInteractMessage: [
        "You to speak to a hurrying student. The student runs into you and falls to the ground. The student quickly",
        "gets up and apologizes to you, asking if you are okay. You are sturdier than you look and you're undamaged.",
        "\"I'm so sorry, I was in such a hurry that I didn't see you there... Say, I haven't seen you here before.",
        "You\'re new here aren\'t-cha?\" the student winks at you, \"Don't worry, there's tons of newbies around today,",
        "why don't you try checking out one of the free intro lessons? I'd show you where to go, but I gotta run to",
        "class. Just head into the Lessons hall and someone should help you out. See you around.\" The student runs",
        "past you. You notice that the student is pretty cute, and probably around your age. Unfortunately, the",
        "student disappears around a corner before you can ask for a name.",
    ],
    lessonsMoveMessage: [
        "You have moved to Lessons. You enter the Lessons hall ready and eager. It's much quieter here, as many of",
        "the lessons have already started. You quickly ushered into the Introductory Lesson, which already begun. You",
        "enter the class on the \"Move Spell.\"",
    ],
    professorInteractMessage: [
        "The professor is difficult to understand, but you pick up just enough to learn 3 things:",
        "1. You can use 'mv' to move things in the world",
        "2. You have to indicate the object and the new location (i.e.: mv OBJECT NEWLOCATION)",
        "3. This spell will only work on certain objects, for example the PracticeDummy objects in the PracticeRoom",
        "<br>",
        "You did not pay enough attention to learn which types of objects are unmovable. Oh well, experimenting was",
        "always more of your style anyways. But be careful!",
    ],
    practiceRoomMoveMessage: [
        "You have moved to PracticeRoom. The room is filled with practice dummies for students to practice their new",
        "spells on.",
    ],
    practiceDummyInteractMessage: "It's a practice dummy",
    youreTooBig: "You're too big to fit into the box.",
    academyInstructionsInteractMessage: [
        "Welcome to the Practice Room. Here you will find practice dummies try your new spells on. Go ahead, give it",
        "a go! If you don't know any spells yet, go back and check out some Lessons.",
    ],
};