var gamevars_en = {
    banner: [
        '<span class="index">© 2024 ShellSaga, All rights reserved.</span>',
        "   _____            _ _ _____                   ",
        "  /  ___| |        | | /  ___|                  ",
        "  \\ `--.| |__   ___| | \\ `--.  __ _  __ _  __ _ ",
        "   `--. \\ '_ \\ / _ \\ | |`--. \\/ _` |/ _` |/ _` |",
        "  /\\__/ / | | |  __/ | /\\__/ / (_| | (_| | (_| |",
        "  \\____/|_| |_|\\___|_|_\\____/ \\__,_|\\__, |\\__,_|",
        "                                     __/ |      ",
        "                                    |___/       ",
        "                                          © 2024",
    ],
    mobileBanner: [
        '<span class="index">© 2024 ShellSaga, All rights reserved.</span>',
        "<br>",
    ],
    welcomeLetter: [
        'Welcome! If you are new to the game, here are some tips: ',
        "<br>",
        'Look at your surroundings with the command "<span class="command">ls</span>"',
        'Move to a new location with the command "<span class="command">cd LOCATION</span>"',
        'You can backtrack with the command "<span class="command">cd ..</span>"',
        'Interact with things in the world with the command "<span class="command">less ITEM</span>"',
        "<br>",
        'If you forget where you are, type "<span class="command">pwd</span>"',
        "<br>",
        'Go ahead, explore. I hope you enjoy what you find. Do <span class="command">ls</span> as your first command',
        "<br>",
    ],
    homeMoveMessage: "You have moved to Home. You are in the comfort of your own home.",
    locationsString: "Locations:",
    itemsString: "Items:",
    rootString: "You have come home!",
    firstRoomString: "You are at the first room. ",
    noLocationString: "There is no place called ",
    commandString: "Command",
    notFoundString: "not found",
    whereString: "You are in ",
    noItemString: "There is no ",
    hereString: " here",
    noLessString: "Pick a different item to less.",
    nothingInterestingString: "Nothing interesting happens.",
    moveErrorString: "You need to move thing A to place B. Use mv [thingA] [placeB].",
    mustBeValidString: "Must be a valid item and location to move it.",
    moveString: "Moved ",
    toString: " to ",
    youreTooBig: "You're too big to fit in there.",
    gardenMoveMessage: [
        "As you step into the garden, you're greeted by the soothing scent",
        "of blooming flowers. Grandma is diligently tending to the plants,",
        "her weathered hands carefully nurturing each one. The vibrant",
        "colors of the flora contrast with the rustic charm of the surroundings.",
        "Beyond Grandma, you notice a pathway leading to the greenhouse,",
        "promising secrets of nature within its glass walls."
    ],
    yardMoveMessage: "You're in the yard.",
    grandmaInteractMessage: [
        "Grandma looks up from her work with a warm smile,",
        "her eyes crinkling at the corners. She gently pats your shoulder",
        "and says, 'I'm busy, my dear grandson. Go and help your grandpa",
        "in the greenhouse. He might have a task for you.'"
    ],    
    greenhouseMoveMessage: [
        "As you step into the greenhouse, a wave of warmth and humidity envelops you.",
        "Rows of thriving plants stretch out in front of you, their leaves glistening",
        "with dewdrops. Grandpa is carefully inspecting each plant, a pair of pruning",
        "shears in his hands. The air is filled with the earthy aroma of soil and the",
        "sweet scent of blossoming flowers. A workbench is cluttered with gardening tools",
        "and seed packets. There's a sense of growth and life in this small, green sanctuary."
    ],
    potatoMessage: "It's a potato.",
    grandpaInteractMessageTask: [
        "Grandpa looks up from his gardening, his eyes twinkling with anticipation.",
        "'Ah, my clever grandson! I have a task for you,' he exclaims.",
        "'You see those potatoes over there - Potato1, Potato2, and Potato3?'",
        "'I need you to move each of them into the Crate using the command <span class=\"command\">mv [potato] Crate</span>.'",
        "'Give it a try, and let me know when you're done.'"
    ],
    grandpaInteractMessageReminder: [
        "Grandpa looks around, a gentle frown appearing on his face.",
        "'You're doing well, my dear, but there are still some potatoes",
        "that need to find their way into the Crate. Remember to use",
        "the <span class=\"command\">mv [potato] Crate</span> command for each one.'"
    ],
    grandpaInteractMessageThanks: [
        "As you successfully move the last potato into the Crate,",
        "Grandpa's face lights up with satisfaction. 'Thank you, my",
        "industrious grandson! Now I can continue my work with ease.'",
        "He gives you a grateful nod and returns to his gardening tasks."
    ],
    grandpaInteractMessageDone: "You did well with the potatoes, thank you!",
};