var gamevars_en = {
    banner: [
        '<span class="index">© ShellSaga, All rights reserved.</span>',
        "   _____            _   _____                   ",
        "  /  ___| |        | | /  ___|                  ",
        "  \\ `--.| |__   ___| | \\ `--.  __ _  __ _  __ _ ",
        "   `--. \\ '_ \\ / _ \\ | |`--. \\/ _` |/ _` |/ _` |",
        "  /\\__/ / | | |  __/ | /\\__/ / (_| | (_| | (_| |",
        "  \\____/|_| |_|\\___|_|_\\____/ \\__,_|\\__, |\\__,_|",
        "                                     __/ |      ",
        "                                    |___/       ",
        "                                                       _                          _ _         ",
        "                                                    __| | ___  __ _ _ __ __ _  __| | | ____ _ ",
        "                                                   / _` |/ _ \\/ _` | '__/ _` |/ _` | |/ / _` |",
        "                                                  | (_| |  __/ (_| | | | (_| | (_| |   < (_| |",
        "                                                   \\__,_|\\___|\\__, |_|  \\__,_|\\__,_|_|\\_\\__,_|",
        "                                                              |___/                     © 2024",
    ],
    welcomeLetter: [
        'Welcome! If you are new to the game, here are some tips: ',
        "<br>",
        'Look at your surroundings with the command "<span class="command">ls</span>"',
        'Move to a new location with the command "<span class="command">cd LOCATION</span>"',
        'You can backtrack with the command "<span class="command">cd ..</span>"',
        'Interact with things in the world with the command "<span class="command">less ITEM</span>"',
        "<br>",
        'If you forget where you are, type "<span class="command">pwd</span>"',
        "<br>",
        'Go ahead, explore. I hope you enjoy what you find. Do <span class="command">ls</span> as your first command',
        "<br>",
    ],
    homeMoveMessage: "You have moved to Home. You are in the comfort of your own home.",
    westernForestMoveMessage: "You step into the mysterious Western Forest.",
    northernMeadowMoveMessage: "The serene Northern Meadow welcomes you.",
    locationsString: "Locations:",
    itemsString: "Items:",
    rootString: "You have come home!",
    firstRoomString: "You are at the first room. ",
    noLocationString: "There is no place called ",
    commandString: "Command",
    notFoundString: "not found",
    whereString: "You are in ",
    noItemString: "There is no ",
    hereString: " here",
    noLessString: "Pick a different item to less.",
    nothingInterestingString: "Nothing interesting happens.",
};